from .core import Rules
from .standard import StandardRules
from .antichess import AntichessRules
from .king_of_the_hill import KingOfTheHillRules
from .three_check import ThreeCheckRules
from .crazyhouse import CrazyhouseRules
from .atomic import AtomicRules
from .horde import HordeRules
from .racing_kings import RacingKingsRules
from .chess960 import Chess960Rules